// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnLimtpWtJx3L966_14diEYhySE0dvQN8',
    appId: '1:126580942842:web:bb76be15981b27093ce643',
    messagingSenderId: '126580942842',
    projectId: 'echosign-5ed8c',
    authDomain: 'echosign-5ed8c.firebaseapp.com',
    storageBucket: 'echosign-5ed8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2w6oROmoBKORlPOpye9VNcT4w1pXt-pw',
    appId: '1:126580942842:android:0e00cdff742a98773ce643',
    messagingSenderId: '126580942842',
    projectId: 'echosign-5ed8c',
    storageBucket: 'echosign-5ed8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9t5Hotb9DMUL_D9f7PwC2JR-SkkJMaIg',
    appId: '1:126580942842:ios:3e4ed9ce0d3a53963ce643',
    messagingSenderId: '126580942842',
    projectId: 'echosign-5ed8c',
    storageBucket: 'echosign-5ed8c.firebasestorage.app',
    iosBundleId: 'com.example.echoSign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9t5Hotb9DMUL_D9f7PwC2JR-SkkJMaIg',
    appId: '1:126580942842:ios:3e4ed9ce0d3a53963ce643',
    messagingSenderId: '126580942842',
    projectId: 'echosign-5ed8c',
    storageBucket: 'echosign-5ed8c.firebasestorage.app',
    iosBundleId: 'com.example.echoSign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnLimtpWtJx3L966_14diEYhySE0dvQN8',
    appId: '1:126580942842:web:a6a21c152fd995883ce643',
    messagingSenderId: '126580942842',
    projectId: 'echosign-5ed8c',
    authDomain: 'echosign-5ed8c.firebaseapp.com',
    storageBucket: 'echosign-5ed8c.firebasestorage.app',
  );
}
